server:
  port: 9191
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/My-Realm/protocol/openid-connect/certs
# Enable this for debugging
#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG